services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_user
      - db_password

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      # Database
      - DB_HOST=db
      - DB_NAME_FILE=/run/secrets/db_user
      - DB_PASSWORD_FILE=/run/secrets/db_password
      # Application
      - SECRET_KEY_FILE=/run/secrets/backend_secret
      - DEBUG=False
      - LOG_LEVEL=DEBUG
      - ALLOWED_HOSTS=localhost 127.0.0.1 backend
    secrets:
      - db_user
      - db_password
      - backend_secret
    depends_on:
      - db

  speech-to-text:
    build: ./speech-to-text
    ports:
      - 5000:5000
    volumes:
      - whisper_cache:/root/.cache/whisper
    restart: always

  suicide-detection:
    build: ./suicide-detection
    ports:
      - 5001:5000
    volumes:
      - suicide_detection_cache:/root/.cache/huggingface

  mood-tracker:
    build: ./mood-tracker
    ports:
      - 5002:5000
    volumes:
      - mood_tracker_cache:/root/.cache/huggingface

  orchestrator:
    build: ./orchestrator
    ports:
      - 8080:8080
    environment:
      # backend
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
      # speech-to-text
      - SPEECH_TO_TEXT_HOST=speech-to-text
      - SPEECH_TO_TEXT_PORT=5000
      # suicide-detection
      - SUICIDE_DETECTION_HOST=suicide-detection
      - SUICIDE_DETECTION_PORT=5000
      - SUICIDE_DETECTION_THRESHOLD=0.6
      - SUICIDE_DETECTION_LABEL=suicide
      # mood-tracker
      - MOOD_TRACKER_HOST=mood-tracker
      - MOOD_TRACKER_PORT=5000
      - MOOD_TRACKER_THRESHOLD=0.75
      # application
      - DEBUG_LEVEL=INFO
    depends_on:
      - backend
      - speech-to-text
      - mood-tracker
      - suicide-detection

  web-app:
    build: ./web-app
    ports:
      - 80:7860
    environment:
      - ORCHESTRATOR_HOST=orchestrator
      - ORCHESTRATOR_PORT=8080 
      - DEBUG_LEVEL=INFO
    depends_on:
      - orchestrator

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  backend_secret:
    file: ./secrets/backend_secret.txt

volumes:
  db_data:
  whisper_cache:
  suicide_detection_cache:
  mood_tracker_cache:
