services:
  whisper-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always # Ensures the service restarts on failure
