BACKEND_HOST= "BACKEND_HOST"
BACKEND_PORT= "BACKEND_PORT"

SPEECH_TO_TEXT_HOST= "SPEECH_TO_TEXT_HOST"
SPEECH_TO_TEXT_PORT= "SPEECH_TO_TEXT_PORT"

SUICIDE_DETECTION_HOST = "SUICIDE_DETECTION_HOST"
SUICIDE_DETECTION_PORT = "SUICIDE_DETECTION_PORT"
SUICIDE_DETECTION_THRESHOLD = "SUICIDE_DETECTION_THRESHOLD"
SUICIDE_DETECTION_LABEL = "SUICIDE_DETECTION_LABEL"

MOOD_TRACKER_HOST= "MOOD_TRACKER_HOST"
MOOD_TRACKER_PORT= "MOOD_TRACKER_PORT"
MOOD_TRACKER_THRESHOLD = "MOOD_TRACKER_THRESHOLD"



