apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ama318/aub_kure-frontend:latest
          ports:
            - containerPort: 7860
          env:
            - name: NEXT_PUBLIC_ORCHESTRATOR_HOST
              value: localhost
            - name: NEXT_PUBLIC_ORCHESTRATOR_PORT
              value: "8080"
            - name: DEBUG_LEVEL
              value: INFO