apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          volumeMounts:
            - name: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
            - name: grafana-provisioning-dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
            - name: grafana-dashboards-definitions
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-provisioning-datasources
          configMap:
            name: grafana-provisioning-config
            items:
              - key: datasources.yaml
                path: datasources.yaml
        - name: grafana-provisioning-dashboards-provider
          configMap:
            name: grafana-provisioning-config
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
        - name: grafana-dashboards-definitions
          configMap:
            name: grafana-dashboards-config