apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-tracker
  labels:
    app: mood-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mood-tracker
  template:
    metadata:
      labels:
        app: mood-tracker
    spec:
      containers:
        - name: mood-tracker
          image: ama318/aub_kure-mood-tracker:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mood-tracker-cache-storage
              mountPath: /root/.cache/huggingface
      volumes:
        - name: mood-tracker-cache-storage
          persistentVolumeClaim:
            claimName: mood-tracker-cache-pvc