apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-to-text
  labels:
    app: speech-to-text
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-to-text
  template:
    metadata:
      labels:
        app: speech-to-text
    spec:
      containers:
        - name: speech-to-text
          image: ama318/aub_kure-speech-to-text:latest
          ports:
            - containerPort: 5000
          env:
            - name: DEBUG_LEVEL
              value: INFO
          volumeMounts:
            - name: whisper-cache-storage
              mountPath: /root/.cache/whisper
      volumes:
        - name: whisper-cache-storage
          persistentVolumeClaim:
            claimName: whisper-cache-pvc