# Check Docker Compose File

# Secrete
SECRET_KEY_FILE = "SECRET_KEY_FILE"
DB_NAME_FILE= "DB_NAME_FILE"
DB_PASSWORD_FILE= "DB_PASSWORD_FILE"

# Envirnoment
DEBUG = "DEBUG"
ALLOWED_HOSTS = "ALLOWED_HOSTS"
DB_HOST = "DB_HOST"
LOG_LEVEL = "LOG_LEVEL"

# Settings
DB_PORT = 5432