apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mood-tracker-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: resizable-hostpath