apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: resizable-hostpath